### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by DaveMyska** [henry-spanka/homebridge-freeathome#30]
Hi Henry,
thanks for your efforts with this. I try to make it work, but every time I get stuck just after logging in to SYSap. I'm sending the logs below. Please, can you help me with this?

Thanks
David

[8/27/2020, 8:21:24 PM] [HB Supervisor] Homebridge Storage Path: /homebridge,
[8/27/2020, 8:21:24 PM] [HB Supervisor] Homebridge Config Path: /homebridge/config.json,
[8/27/2020, 8:21:24 PM] [HB Supervisor] Logging to /homebridge/homebridge.log,
[8/27/2020, 8:21:24 PM] [HB Supervisor] OS: Linux 5.4.51-v7+ arm,
[8/27/2020, 8:21:24 PM] [HB Supervisor] Node.js v12.18.3 /usr/local/bin/node,
[8/27/2020, 8:21:24 PM] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge,
[8/27/2020, 8:21:24 PM] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js,
[8/27/2020, 8:21:24 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules,
[8/27/2020, 8:21:24 PM] [HB Supervisor] Started Homebridge v1.1.2 with PID: 361,
[8/27/2020, 8:21:25 PM] Loaded config.json with 0 accessories and 2 platforms.,
[8/27/2020, 8:21:25 PM] ---,
[8/27/2020, 8:21:27 PM] Loaded plugin: homebridge-dummy@0.4.1,
[8/27/2020, 8:21:27 PM] Registering accessory 'homebridge-dummy.DummySwitch',
[8/27/2020, 8:21:27 PM] ---,
[8/27/2020, 8:21:28 PM] Loaded plugin: homebridge-freeathome@2.0.3,
homebridge API version: 2.6,
[8/27/2020, 8:21:28 PM] Registering platform 'homebridge-freeathome.free@home',
[8/27/2020, 8:21:28 PM] Registering platform 'homebridge-freeathome.BuschJaegerSysAp',
[8/27/2020, 8:21:28 PM] ---,
[8/27/2020, 8:21:28 PM] Loaded plugin: homebridge-config-ui-x@4.26.0,
[8/27/2020, 8:21:28 PM] Registering platform 'homebridge-config-ui-x.config',
[8/27/2020, 8:21:28 PM] ---,
[8/27/2020, 8:21:28 PM] Loading 2 platforms...,
[8/27/2020, 8:21:28 PM] [Config] Initializing config platform...,
[8/27/2020, 8:21:28 PM] [Config] Running in Service Mode,
[8/27/2020, 8:21:28 PM] [free@home] Initializing free@home platform...,
[8/27/2020, 8:21:28 PM] [free@home] Initialising BuschJaeger Plugin,
[8/27/2020, 8:21:28 PM] [free@home] Will try to connect to the SysAP at 192.168.1.2,
[8/27/2020, 8:21:28 PM] [free@home] Trying to connect to SysAP,
[8/27/2020, 8:21:31 PM] [Config] Homebridge Config UI X v4.26.0 is listening on :: port 8080,
[8/27/2020, 8:21:34 PM] [free@home] Connected as 08379667-e9ac-43ed-a986-85cb700dc051@busch-jaeger.de/freeathome-api,
[8/27/2020, 8:21:34 PM] [free@home] Sent Authenticator,
[8/27/2020, 8:21:34 PM] [free@home] Received Local Key,
[8/27/2020, 8:21:34 PM] [free@home] Sent New Session Request,
[8/27/2020, 8:21:34 PM] [free@home] Sent Login SASL Message,
[8/27/2020, 8:21:34 PM] [free@home] Received SASL Challenge,
[8/27/2020, 8:21:35 PM] [free@home] Sent SASL Challenge Response,
[8/27/2020, 8:21:35 PM] [free@home] Received SASL Login Confirmation,
[8/27/2020, 8:21:35 PM] [free@home] Successfully Authenticated,
[8/27/2020, 8:21:35 PM] [free@home] Announced Capabilities to System Access Point,
[8/27/2020, 8:21:35 PM] [free@home] Requested Master Data Structure from System Access Point,
[8/27/2020, 8:21:37 PM] [free@home] Received Master Update from System Acccess Point,
(node:361) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined,
    at Function.parseDeviceData (/homebridge/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/XmlParser.js:110:106),
    at Function.parseMasterUpdate (/homebridge/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/XmlParser.js:17:21),
    at SystemAccessPoint.<anonymous> (/homebridge/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:314:53),
    at Generator.next (<anonymous>),
    at /homebridge/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:8:71,
    at new Promise (<anonymous>),
    at __awaiter (/homebridge/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:4:12),
    at SystemAccessPoint.handleRpcCallResult (/homebridge/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:293:16),
    at SystemAccessPoint.<anonymous> (/homebridge/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:267:26),
    at Generator.next (<anonymous>),
(node:361) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1),
(node:361) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.,

**Comment by henry-spanka** [comment]
Hi,
make sure that you have assigned each device to a room. If that does not fix your issue please send me a backup of your SysAp configuration ("Projektsicherung") to my email address (linked on my GitHub profile).

**Comment by DaveMyska** [comment]
Hi,
thanks for you advise, that was really it. Now its working!:)

Once again thanks a lot.

David
