### ISSUE TITLE
Garagedoor setup fault

### ISSUE THREAD

**Issue by DaveMyska** [henry-spanka/homebridge-freeathome#48]
Hi Henry,

I'm still trying to control of garage door in homekit but with no success. The easiest way for me would be adding support for trigger actuator (mentioned in problem #28). Since this is not supported yet I tried to setup garagedoor according to your garagedoor tutorial - with no succes too. Can you see where the problem is?

Many thanks
David

My setup is:
            "platform": "free@home",
            "sysIP": "xxxx",
            "username": "xxxx",
            "password": "xxxx",
            "mappings": {
                "ABB22A693151": {
                    "garagedoor": {
                        "ch0011": {
                            "movingUpTime": 15,
                            "movingDownTime": 15,
                            "triggerTime": 1
       
Homebridge returns error:

[2/6/2021, 11:58:28 AM] [free@home] initialising actuator garagedoor with uuid ABB22A693151ch0011
[2/6/2021, 11:58:28 AM] [free@home] Unexpected error while processing stanza event
[2/6/2021, 11:58:28 AM] [free@home] Error: EACCES: permission denied, mkdir '/run/s6/services/homebridge-config-ui-x/.node-persist'
    at Object.mkdirSync (fs.js:921:3)
    at sync (/homebridge/node_modules/homebridge-freeathome/node_modules/mkdirp/index.js:72:13)
    at Function.sync (/homebridge/node_modules/homebridge-freeathome/node_modules/mkdirp/index.js:78:24)
    at LocalStorage.parseStorageDirSync (/homebridge/node_modules/homebridge-freeathome/node_modules/node-persist/src/local-storage.js:600:20)
    at LocalStorage.initSync (/homebridge/node_modules/homebridge-freeathome/node_modules/node-persist/src/local-storage.js:141:14)
    at Object.nodePersist.initSync (/homebridge/node_modules/homebridge-freeathome/node_modules/node-persist/src/node-persist.js:37:32)
    at new BuschJaegerGarageDoorAccessory (/homebridge/node_modules/homebridge-freeathome/lib/BuschJaegerGarageDoorAccessory.js:13:18)
    at BuschJaegerApPlatform.initializeAccessory (/homebridge/node_modules/homebridge-freeathome/index.js:120:16)
    at BuschJaegerApPlatform.transformAccessories (/homebridge/node_modules/homebridge-freeathome/index.js:80:38)
    at BuschJaegerApPlatform.processMessage (/homebridge/node_modules/homebridge-freeathome/index.js:245:14) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/run/s6/services/homebridge-config-ui-x/.node-persist'
}
[2/6/2021, 11:58:28 AM] [free@home] EACCES: permission denied, mkdir '/run/s6/services/homebridge-config-ui-x/.node-persist'

**Comment by captainkoehler** [comment]
Support for trigger actuators would be awesome!

**Comment by henry-spanka** [comment]
Please open a new feature request for this if it is still relevant.
