### ISSUE TITLE
ENOTFOUND undefined

### ISSUE THREAD

**Issue by Saesh123** [henry-spanka/homebridge-freeathome#60]
Hi, 
I am testing Homebridge for the first time. Unfortunately, i fail with your plugin. I can't get a connection to the AP.
Unfortunately, I didn't find an entry in the issues.
Do you have a solution for me?

[31/01/2022, 21:48:42] [BuschJaegerSysAp] Initializing free@home platform... [31/01/2022, 21:48:42] [BuschJaegerSysAp] Initialising BuschJaeger Plugin [31/01/2022, 21:48:42] [BuschJaegerSysAp] Will try to connect to the SysAP at 192.168.178.105 [31/01/2022, 21:48:42] [BuschJaegerSysAp] Trying to connect to SysAP [31/01/2022, 21:48:42] [BuschJaegerSysAp] Initializing BuschJaegerSysAp platform... [31/01/2022, 21:48:42] [BuschJaegerSysAp] Initialising BuschJaeger Plugin [31/01/2022, 21:48:42] [BuschJaegerSysAp] Will try to connect to the SysAP at undefined [31/01/2022, 21:48:42] [BuschJaegerSysAp] Trying to connect to SysAP [31/01/2022, 21:48:42] [BuschJaegerSysAp] getaddrinfo ENOTFOUND undefined [31/01/2022, 21:48:45] [BuschJaegerSysAp] Connected as installer@busch-jaeger.de/freeathome-api [31/01/2022, 21:48:45] [BuschJaegerSysAp] Sent Authenticator [31/01/2022, 21:48:45] [BuschJaegerSysAp] Received Local Key [31/01/2022, 21:48:45] [BuschJaegerSysAp] Sent New Session Request [31/01/2022, 21:48:45] [BuschJaegerSysAp] Sent Login SASL Message [31/01/2022, 21:48:46] [BuschJaegerSysAp] Received SASL Challenge [31/01/2022, 21:48:46] [BuschJaegerSysAp] Sent SASL Challenge Response [31/01/2022, 21:48:46] [BuschJaegerSysAp] Received SASL Login Confirmation [31/01/2022, 21:48:46] [BuschJaegerSysAp] Successfully Authenticated [31/01/2022, 21:48:46] [BuschJaegerSysAp] Announced Capabilities to System Access Point [31/01/2022, 21:48:46] [BuschJaegerSysAp] Requested Master Data Structure from System Access Point [31/01/2022, 21:48:46] [BuschJaegerSysAp] Received Master Update from System Acccess Point [31/01/2022, 21:48:47] TypeError: Cannot read properties of undefined (reading 'name') at Function.parseDeviceData (/usr/local/lib/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/XmlParser.js:110:106) at Function.parseMasterUpdate (/usr/local/lib/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/XmlParser.js:17:21) at SystemAccessPoint.<anonymous> (/usr/local/lib/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:314:53) at Generator.next (<anonymous>) at /usr/local/lib/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:8:71 at new Promise (<anonymous>) at __awaiter (/usr/local/lib/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:4:12) at SystemAccessPoint.handleRpcCallResult (/usr/local/lib/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:293:16) at SystemAccessPoint.<anonymous> (/usr/local/lib/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:267:26) at Generator.next (<anonymous>) [31/01/2022, 21:48:47] Got SIGTERM, shutting down Homebridge... [31/01/2022, 21:48:52] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null

**Comment by nixmeer** [comment]
Hello, 

I think I got the same issue. All devices are configured and assigned to rooms. Still this error:

```[15/02/2022, 19:30:21] TypeError: Cannot read properties of undefined (reading 'name')
    at Function.parseDeviceData (/usr/lib/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/XmlParser.js:110:106)
    at Function.parseMasterUpdate (/usr/lib/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/XmlParser.js:17:21)
    at SystemAccessPoint.<anonymous> (/usr/lib/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:314:53)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:4:12)
    at SystemAccessPoint.handleRpcCallResult (/usr/lib/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:293:16)
    at SystemAccessPoint.<anonymous> (/usr/lib/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:267:26)
    at Generator.next (<anonymous>)```

Has anyone any idea?

**Comment by nixmeer** [comment]
Created an issue [here](https://github.com/henry-spanka/freeathome-api/issues/45#issue-1140024800) since the error occurs in the freeathome-api

**Comment by b3ss1k** [comment]
Hello, a similar problem, the error seems to be the same. Is there any solution to this problem ?

And another question, sometimes curtains are not added for an unclear reason, what can be done about it?

**Comment by b3ss1k** [comment]
Hello, I wanted to ask such a question, for some reason I do not add curtains to homebirdge for some unknown reason. Moreover, I have several objects and everything works fine on some, and on some curtains are simply not visible. Any suggestions why it might not work ?
