### ISSUE TITLE
TypeError cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by korneliuscode** [henry-spanka/homebridge-freeathome#64]
Hi, I’m trying to setup the plug-in but it does not start giving the following error

```
TypeError cannot read properties of undefined (reading 'name')
at Function.parseDeviceData (/var/ lib/homebridge/node_modules/homebridge
-freeathome/ node_modules/freeathome-ap i/dist/lib/XmIParser.js:111:106)
at Function.parseMasterUpdate (/ va r/lib/homebridge/node_modules/homebrid ge-freeathome/ node_modules/freeathome-api/dist/lib/XmlParser.js:18:21)
at SystemAccessPoint.<anonymous> ( /var/lib/homebridge/node_modules/homeb ridge-freeathome/node modules/freeatho me-api/dist/lib/SystemAccessPoint.js:3
26:53)
at Generator.next (<anonymous>)
at /var/lib/homebridge/node module s/homebridge-freeathome/node modules/f reeathome-api/dist/lib/SystemAccessPoi nt.js:8:71
at new Promise (<anonymous>)
at awaiter /var/lib/homebridge/ node_modules/homebridge-freeathome/nod e _modules/freeathome-api/dist/lib/Syst emAccessPoint.js:4:12)
at SystemAccessPoint.handleRpcCall
Result /var/lib/homebridge/node_modul es/homebridge-freeathome/node_modules/ freeathome-api/dist/lib/SystemAccessPo int.js:305:16)
at SystemAccessPoint.<anonymous> ( /var/lib/homebridge/node_modules/homeb ridge-freeathome/ node_ modules/freeatho…
me-api/dist/lib/SystemAccessPoint.js:2
73:26)
at Generator.next (<anonymous>)

```

```
AssertionError
[ERR_ASSERTION]: Cannot generate setup
URI on an accessory that isn't published yet!
at Bridge.Accessory.setupURI (/var /lib/homebridge/node modules/homebridg e/node modules/hap-nodejs/src/lib/Acce ssory.ts:994:11)
at Server.setServerStatus (/var/li b/homebridge/node modules/homebridge/s rc/server.ts:155:45)
at Server.teardown (/var/lib/homeb ridge/node modules/homebridge/src/serv er.ts:199:10)
at signalHandler /var/lib/homebri dge/node_modules/homebridge/src/cli.ts
:93:12)
at process.emit (node:events:513:2
8 )
at process.emit (/var/lib/homebrid ge/node_modules/homebridge/node_module

```

**Comment by henry-spanka** [comment]
Hi. Make sure that all of your accessories have a name defined in the free@home UI. If it is still not working, please send me your free@home backup via e-mail (see my GitHub profile).

**Comment by henry-spanka** [comment]
please see #65 for a solution.
