### ISSUE TITLE
floorId && roomId ? floorData[floorId.getText()].rooms[roomId.getText()].name : ""

### ISSUE THREAD

**Issue by deniskern** [henry-spanka/homebridge-freeathome#65]
Hi, i'm getting following error 

`/var/lib/homebridge/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/XmlParser.js:111 "room": floorId && roomId ? floorData[floorId.getText()].rooms[roomId.getText()].name : "",
TypeError: Cannot read properties of undefined (reading 'name')
    at Function.parseDeviceData (/var/lib/homebridge/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/XmlParser.js:111:106)
    at Function.parseMasterUpdate (/var/lib/homebridge/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/XmlParser.js:18:21)
    at SystemAccessPoint.<anonymous> (/var/lib/homebridge/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:326:53)
    at Generator.next (<anonymous>)
    at /var/lib/homebridge/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/var/lib/homebridge/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:4:12)
    at SystemAccessPoint.handleRpcCallResult (/var/lib/homebridge/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:305:16)
    at SystemAccessPoint.<anonymous> (/var/lib/homebridge/node_modules/homebridge-freeathome/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:273:26)
    at Generator.next (<anonymous>)`

**Comment by henry-spanka** [comment]
Hi,
please make sure that each actuator and floor has a name defined.

**Comment by henry-spanka** [comment]
This issue was caused by a bug in the library henry-spanka/freeathome-api#45. The issue has now been resolved. Please try to update the rpm dependencies to get the latest version of the *freeathome-api* package (>= 1.1.3).
